---
title: "Final_Project_Practice"
author: "Aldric Martinez-Olson"
date: "2/25/2021"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)     # for data cleaning and plotting
library(gardenR)       # for Lisa's garden data
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(palmerpenguins)# for Palmer penguin data
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(transformr)    # for "tweening" (gganimate)
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
#library(shiny)         # for creating interactive apps
theme_set(theme_minimal())
library(readr)
```

```{r}
bird_migration <- read_csv("~/Desktop/bird_migration.csv")
temperature_change <- read_csv("~/Desktop/Environment_Temperature_change_E_All_Data_NOFLAG.csv")
```

```{r}
temperature_change %>% 
  pivot_longer(cols = Y1961:Y2019, 
               names_to = "year", 
               values_to = "temperature") %>% 
  separate(year, into = c("junk", "year"), sep = "Y", convert = TRUE)
  #str_replace(temperature_change$year, "Y", "")
```

```{r}
bird_migration %>% 
  select(-device_info_serial) %>% 
  separate(date_time, c("date", "time"), sep = " ") %>% 
  mutate(date_tag = date) %>% 
  separate(date_tag,
           c("Year", "Month", "Day"))
```

1. Color by altitude ()
2. Comparison of 
3. Sanne